version: '3'

services:
  dbmysql:
    build: ./db
    environment:
      MYSQL_DATABASE: pan
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3307:3307"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
  frontend:
    build: ./react_ArquiSoft
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "3000:3000"
  backend:
    build: ./ServicioWeb_ArqSoft
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "3306:3306"