version: '3'

services:
  mvc:
    build: ./db
    environment:
      MYSQL_DATABASE: pan
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root","-p root"]
      timeout: 20s
      retries: 10
  front:
    build: ./React_ArquiSoft
    depends_on:
      mvc:
        condition: service_healthy
    ports:
      - "3000:3000"
  back:
    build: ./ServicioWeb_ArqSoft
    restart: on-failure
    depends_on:
      mvc:
        condition: service_healthy
    ports:
      - "3307:3307"